install.packages("data.table")
install.packages("devtools")
install.packages("ggpubr")
install.packages("ggsci")
install_github("microbiome/microbiome")
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
