install.packages("data.table")
install.packages("devtools")
install.packages("ggpubr")
install.packages("ggsci")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("microbiome")
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
